language: node_js

node_js:
  - "4.4"

cache:
  directories:
    - node_modules
    - temp
    - app/node_modules
    - $HOME/.electron
    - $HOME/.cache

sudo: required 
dist: trusty 

before_install:
  sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
  
script:
  - npm list 
  - npm run dist
  
env:
  global:
    secure: JtPr31jRxOSp8XFeGcgPSGm2FfjnL6ja/23KgCwMapIZQCs24FB6l1jxhh7Fqc6683vbHqJW54vUM6pXneQqMG9r8iXskkE0foyXLoGVkn9a0NyjgFWVuEzlwxC4ccV7VS8zhsQlGERA6bdeQ8WotZu8iu4YMETX/TwyB5zoX0xcvZD7s+xh8sZkYvt7j1xFcMM19E5YOoWI1ZwME7+mirI0s6LCU8opzvbg+c2HxOEqHuvZe3LREH6JToCGVuk0bk6hcgF/4GnMiEpDdSNMGacW5OQ5eLbPXJQj6YyHSWbWcgaOwqQdO+Lx2zZouZ7Y4xdr2dYR8L90KKIxHdLc0nV8DCveT+QXnDuPjkklXdM2v9jpjrNSK2bNjvKKqJKN4FBgU5fVuFnTQTC1xN2YJboho/lacKKQtAnQuk8HA4atBGWlpJtO/EYu8tmy/4gl1Ij8+O7IZCmmHJKIdcaYW9yeU/O2nEfyGgCFM1ZFPwAGOojNNZAVR1NVNOYh4tF5oIHssJ9tby7MsbA3mZ6Jv5dIgGzIHxb2bADVqqSSWtRv15haYv48cRaQ2FCkNV6qi4ffMroIxY51FEwVWTwyzh+pS/BL1vSR0POd1J05v+Sbg/II6tAcIUMhXv1PLl//LZiwfQC8S+26Jyl9v0ZGUsnd+KQw51RLSIXL8wQVpMc=
