language: node_js
node_js:
  - "4.4"
cache:
  directories:
    - node_modules
    - app/node_modules
sudo: required
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get -qq update
  - sudo apt-get install --no-install-recommends -y wine1.8 mono-devel ca-certificates-mono
script:
  - npm run dist
