language: node_js

node_js:
  - "4.4"

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron
    - $HOME/.cache

sudo: required 
dist: trusty 

before-install:
  sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
script:
  - npm run dist
