#version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 4.4 x64
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run dist

artifacts:
  - path: dist\win\*.exe

test: off

deploy:
  release: ballast-v$(appveyor_build_version)-win
  description: 'Ballast v$(appveyor_build_version) (Windows)'
  provider: GitHub
  auth_token:
    secure: 2UWID8annSgDmjvOW4PiFoW7LCz1F3euGszzrjgEY9OdwDRlbuu88wfmShj0tQI0
  artifact: /.*/
  draft: true
  on:
    branch: master                # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only