version: '0.1.0.{build}'

platform:
  - x64

cache:
  - node_modules
  - temp
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

environment:
  GH_TOKEN:
    secure: IhA6RlRE79jPEwoTknXltoyllUvnXE+IQw+Rmkqx31Iu0KKErVVUvlafo236Cewb

install:
  - ps: Install-Product node 4.4 x64
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run dist

artifacts:
  - path: dist\win\*.exe

test: off